name: Java CI with Maven

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        maven-version: '3.9.6'  # 指定 Maven 版本为 3.9.6
        cache: maven

    - name: Build with Maven
      run: mvn clean install -DskipTests=true --file pom.xml

    # Upload JAR files
    - name: Upload JAR files
      uses: actions/upload-artifact@v3  # 使用 v3 版本
      with:
        name: my-app-jars
        path: target/*.jar  # 上传 target 目录下所有的 JAR 文件
